Create bot.py
VadimGK/MSAI21-Telegram-short-unsort-link-Bot pull request #8
Opened 2022-02-03 02:48 UTC by VladGKulikov

New code for our bot

2022-02-03 20:23 UTC, nlevashov requested changes

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +        uri = unshortener.unshorten(link)
если напишут 2 пользователя +- одновременно, один из них получит реплику другого. это критичный баг

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +    if a == "short":
лучше использовать elif, так как это взаимоисключающие ситуации. сейчас эта проверка случится, даже если прошлая прошла

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +    a = query.data
лучше назвать переменную command или payload, тогда будет понятно, что в ней

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +            query.edit_message_text("Shorted url 👇🏼:\n" + str(response))
на мой субъектинвый взгляд с f-строками подобные конструкции будут выглядеть лучше

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +        res = '\n' + i.short_link + res
такое лучше делать с конструкцией `'\n'.join(i.short_link for i in reversed(persons))`

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +    k = int(random.uniform(0, 1000))
random.randint

2022-02-03 20:23 UTC, nlevashov commented on bot.py
> +    short_link = Required(str)
модель содержит ссылки, а называется Person, это вводит в заблуждение

2022-02-04 01:05 UTC, VladGKulikov commented on bot.py
> +    short_link = Required(str)
Done - Rename class  Person to ShortLink

2022-02-04 01:16 UTC, VladGKulikov commented on bot.py
> +    short_link = Required(str)
and variable "persons" to short_links

2022-02-04 01:22 UTC, VladGKulikov commented on bot.py
> +    a = query.data
Переименовал переменную 'a' в command

2022-02-04 01:26 UTC, VladGKulikov commented on bot.py
> +    if a == "short":
Изменил if  на elif

2022-02-04 01:51 UTC, VladGKulikov commented on bot.py
> +        res = '\n' + i.short_link + res
Убрал for, сделал конструкцию - '\n'.join(i.short_link for i in reversed(persons))

2022-02-04 01:53 UTC, VladGKulikov commented on bot.py
> +    k = int(random.uniform(0, 1000))
сделал   k = int(random.randint(0, 1000))

2022-02-04 01:58 UTC, VladGKulikov commented on bot.py
> +            query.edit_message_text("Shorted url 👇🏼:\n" + str(response))
Сделал f строку - f'Shorted url 👇🏼:\n{str(response)}'

2022-02-04 03:12 UTC, VladGKulikov commented on bot.py
> +        uri = unshortener.unshorten(link)
Исправил критическое замечание - сделал словарь для хранения ссылок по id пользователя, убрав глобальную переменную link.

dict_users_links = {}
....
при запросе сохраняю в этом словаре по id пользователя его запрошенную ссылку
        user = update.message.from_user
        dict_users_links[user['id']] = link
....
и при выборе и обращении к фактическому short/unshort  - беру по id пользователя из словаря сохраненную  в нем ссылку
    user_id = update.callback_query.message.chat['id']
    link = dict_users_links[user_id]

и с ней уже работаю дальше.

2022-04-01 06:05 UTC, VadimGK commented
Ok. Well done!

2022-04-01 06:05 UTC, closed without merging